### ISSUE TITLE
main.save is not a function

### ISSUE THREAD

**Issue by DevBungfro** [drezzyts/atlas.db#1]
I get this error:
 await main.save()
               ^

TypeError: main.save is not a function

My Code: 
```js
const Atlas = require('atlas.db');

const Database = new Atlas.Database();

const MainStructures = new Atlas.Structure({
    totalVisits: { type: Array, default: [] },
    totalGenerations: { type: Number, default: 0 },
    visits: { type: Array, default: [] },
    generations: { type: Array, default: [] }
});

const Main = Database.createTable('main', MainStructures);

const main = Main.get('main') || Main.create({
    id: 'main',
    totalVisits: [],
    totalGenerations: 0,
    visits: [],
    generations: []
})



module.exports = { main: main };
```

**Comment by drezzyts** [comment]
This error is probably due to the way you exported, try making this change in your code
```diff
- module.exports = { main: main }
+ module.exports = { main }
```

**Comment by DevBungfro** [comment]
> This error is probably due to the way you exported, try making this change in your code
> 
> ```diff
> - module.exports = { main: main }
> + module.exports = { main }
> ```

Got the same error, tried doing that and even tried saving it in the same file and it doesn't work.

**Comment by drezzyts** [comment]
Which version are you using?

**Comment by DevBungfro** [comment]
Latest I guess

**Comment by drezzyts** [comment]
Can you send me the part of your code that you try to make changes to "main"?

**Comment by DevBungfro** [comment]
main.totalVisits["test"] = 1;
main.save();
console.log(main.totalVisits);

**Comment by drezzyts** [comment]
Can you message me on discord? drezzy#5808
